version: '3.2'

services:

  mysql: # Mysql container
    container_name: development-mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./logs:/var/log/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: sample
      MYSQL_USER:     admin
      MYSQL_PASSWORD: passwd
      TZ: Asia/Tokyo
    ports:
      - 3306:3306

  pma: # phpMyAdmin container
    container_name: php_my_admin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: passwd
    ports:
      - 8080:80
    links:
      - mysql:db
